### ISSUE TITLE
Just some clarifications & Questions

### ISSUE THREAD

**Issue by kezenwa** [leafsphp/fetch#1]
What's difference between **https://github.com/leafsphp/fetch**  and  **https://github.com/leafsphp/http**  and   **https://github.com/leafsphp/eien**  ?

Isn't it possible to have a single Request & response class, then have **https://github.com/leafsphp/fetch**  and  **https://github.com/leafsphp/http**  and   **https://github.com/leafsphp/eien** as adapters ?

Which among **https://github.com/leafsphp/fetch**  and  **https://github.com/leafsphp/http**  and   **https://github.com/leafsphp/eien** is better suited for which use Cases ?

**Comment by mychidarko** [comment]
Hi @kezenwa, so sorry, I just saw this issue.

- This library fetch is something like axios, it's used for making network requests, basically.

- https://github.com/leafsphp/http is a handler for requests coming into your app, allows you to output data from your app, configure headers and other stuff related to requests and responses.

- Eien is an HTTP server that is powered by [swoole](https://openswoole.com/). It basically allows Leaf to run asynchronously and benefit from stateful requests

These 3 are all different libraries with entirely different use-cases.
