### ISSUE TITLE
Call to undefined function Leaf\fetch()

### ISSUE THREAD

**Issue by jingguanzhang** [leafsphp/fetch#3]
I have run "composer require leafs/fetch" to install it, 
but it prompts Call to undefined function Leaf\fetch(), 
which does not work properly in php8.3 version
![QQ截图20240327195511](https://github.com/leafsphp/fetch/assets/156168287/cb07813a-4630-4414-a344-1fcc046be0b8)

**Comment by mychidarko** [comment]
This has been fixed, will publish a new version in the next few days
